services:
  mongo:
    restart: always
    image: mongo:8.0.1
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

networks:
  enlace-platform:
    external: true
